version: '3'
services: # Here we define our service(s)
  app:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    extra_hosts:
      - "localhost:192.168.0.0"
    #command: /bin/sh